# Generated by Django 5.1.3 on 2025-01-16 01:49

import page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('beauty', 'Beauty & Skincare'), ('food', 'Food & Beverage'), ('others', 'Others')], default='food', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='This will be auto generated', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to=page.models.image_directory_path, verbose_name='Ads Image')),
                ('link', models.URLField(blank=True, help_text='Optional: URL to redirect when the banner is clicked.', max_length=500, null=True, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers will display first.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide the banner on the homepage.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Ads',
                'verbose_name_plural': 'Ads',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('beauty', 'Beauty & Skincare'), ('food', 'Food & Beverage'), ('others', 'Others')], default='food', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='This will be auto generated', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to=page.models.image_directory_path, verbose_name='Banner Image')),
                ('link', models.URLField(blank=True, help_text='Optional: URL to redirect when the banner is clicked.', max_length=500, null=True, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers will display first.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide the banner on the homepage.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('beauty', 'Beauty & Skincare'), ('food', 'Food & Beverage'), ('others', 'Others')], default='food', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='This will be auto generated', max_length=100, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True, verbose_name='slogan')),
                ('discount_info', models.CharField(blank=True, default='Up to 50% Off', max_length=200, null=True, verbose_name='Discount Info')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to=page.models.image_directory_path, verbose_name='Campaign Image')),
                ('link', models.URLField(blank=True, help_text='Optional: URL to redirect when the banner is clicked.', max_length=500, null=True, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers will display first.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to show/hide the banner on the homepage.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
