# Generated by Django 5.1.3 on 2025-05-08 12:22

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='dep', unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='business.business', verbose_name='Business')),
                ('user', models.ForeignKey(blank=True, editable=False, help_text='This field is automatically set to the logged-in user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.CharField(help_text='Unique Employee ID', max_length=10, unique=True, verbose_name='Employee Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('on_leave', 'On Leave'), ('retired', 'Retired')], default='active', max_length=20, verbose_name='Employment Status')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20, verbose_name='Employment Type')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Termination Date')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='business.business', verbose_name='Business')),
                ('department', models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='employee.department', verbose_name='Department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employee.employee', verbose_name='Manager')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='Emergency Contact Phone')),
                ('personal_notes', models.TextField(blank=True, verbose_name='Personal Notes')),
                ('additional_info', models.JSONField(blank=True, null=True, verbose_name='Additional Information')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's Name")),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spouse Name')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow')], max_length=10, null=True, verbose_name='Marital Status')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Blood Group')),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('christianity', 'Christianity'), ('others', 'Others')], max_length=20, null=True, verbose_name='Religion')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationality')),
                ('nid', models.CharField(blank=True, max_length=20, null=True, verbose_name='National ID')),
                ('mobile_office', models.CharField(blank=True, max_length=15, null=True, verbose_name='Office Mobile Number')),
                ('email_office', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Office Email Address')),
                ('driving_license', models.CharField(blank=True, max_length=20, null=True, verbose_name='Driving License')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='employee.employee', to_field='emp_no')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255, verbose_name='Institution')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('field_of_study', models.CharField(max_length=255, verbose_name='Field of Study')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('employee_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='employee.employeedetails', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Certification Name')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Issued By')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('employee_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='employee.employeedetails', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='pos', unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Position')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('salary_grade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salary Grade')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='business.business', verbose_name='Business')),
                ('user', models.ForeignKey(blank=True, editable=False, help_text='This field is automatically set to the logged-in user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='employee.position', verbose_name='Position'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('organization', models.CharField(max_length=255, verbose_name='Organization')),
                ('completion_date', models.DateField(verbose_name='Completion Date')),
                ('employee_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='employee.employeedetails', verbose_name='Employee')),
            ],
        ),
    ]
