# Generated by Django 5.1.3 on 2025-05-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_product_manufacturer_delete_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
    ]
