# Generated by Django 5.1.3 on 2025-05-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_supplier_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='supplier',
        ),
    ]
