# Generated by Django 5.1.3 on 2025-05-08 12:19

import django.db.models.deletion
import shortuuid.django_fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', editable=False, length=10, max_length=30, prefix='con', unique=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('supplier', 'Supplier'), ('manufacturer', 'Manufacturer'), ('other', 'Other')], default='customer', max_length=20, verbose_name='Contact Type')),
                ('supplier_business_name', models.CharField(blank=True, help_text='Only for supplier business names', max_length=255, null=True, verbose_name='Supplier Business Name')),
                ('prefix', models.CharField(blank=True, help_text='e.g., Mr., Ms., Dr.', max_length=20, null=True, verbose_name='Prefix')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('contact_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Contact ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Number')),
                ('address_line1', models.TextField(blank=True, null=True, verbose_name='Address Line 1')),
                ('address_line2', models.TextField(blank=True, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='ZIP Code')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Shipping Address')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
                ('landline', models.CharField(blank=True, max_length=20, null=True, verbose_name='Landline')),
                ('alternate_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternate Number')),
                ('pay_term_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Payment Term Number')),
                ('pay_term_type', models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months')], max_length=10, null=True, verbose_name='Payment Term Type')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Credit Limit')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Balance')),
                ('total_rp', models.PositiveIntegerField(default=0, verbose_name='Total Reward Points')),
                ('total_rp_used', models.PositiveIntegerField(default=0, verbose_name='Total Reward Points Used')),
                ('total_rp_expired', models.PositiveIntegerField(default=0, verbose_name='Total Reward Points Expired')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('is_default', models.BooleanField(default=False, help_text='Indicates if this is the primary or default contact for the business.', verbose_name='Is Default')),
                ('is_walk_in', models.BooleanField(default=False, help_text='Indicates if this is the walk-in-customer for the sales.')),
                ('is_export', models.BooleanField(default=False, help_text='Marks whether this contact is associated with export transactions or operations.', verbose_name='Is Export Contact')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('customer_group_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Customer Group ID')),
                ('custom_field1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Field 1')),
                ('custom_field2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Field 2')),
                ('custom_field3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Field 3')),
                ('custom_field4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Field 4')),
                ('custom_field5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom Field 5')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tags', models.JSONField(blank=True, default=list, null=True, verbose_name='Tags')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('social_media', models.JSONField(blank=True, default=dict, null=True, verbose_name='Social Media Links')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Preferred Currency')),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Terms')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business.business', verbose_name='Business')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cid'], name='contact_idx_cid'), models.Index(fields=['business'], name='contact_idx_business'), models.Index(fields=['type'], name='contact_idx_type'), models.Index(fields=['email'], name='contact_idx_email'), models.Index(fields=['mobile'], name='contact_idx_mobile'), models.Index(fields=['contact_id'], name='contact_idx_contact_id'), models.Index(fields=['is_active'], name='contact_idx_is_active'), models.Index(fields=['dob'], name='contact_idx_dob'), models.Index(fields=['created_at'], name='contact_idx_created_at'), models.Index(fields=['updated_at'], name='contact_idx_updated_at')],
            },
        ),
    ]
