from django.contrib import admin
from .models import Patient

@admin.register(Patient)
class PatientAdmin(admin.ModelAdmin):
    # Fields to display in the list view
    list_display = ('patient_id', 'first_name', 'last_name', 'gender', 'date_of_birth', 'is_active', 'registration_date')
    
    # Fields to filter by
    list_filter = ('gender', 'is_active', 'registration_date')
    
    # Fields to search by
    search_fields = ('patient_id', 'first_name', 'last_name', 'email', 'phone')
    
    # Fields to use for ordering
    ordering = ('-registration_date', 'patient_id')
    
    # Read-only fields (for autogenerated fields)
    readonly_fields = ('patient_id', 'registration_date', 'last_updated')
    
    # Form fieldsets for organization
    fieldsets = (
        ("Basic Information", {
            'fields': ('patient_id', 'first_name', 'last_name', 'date_of_birth', 'gender', 'phone', 'email', 'father_name', 'mother_name', 'spouse_name')
        }),
        ("Address & Contact", {
            'fields': ('address', 'emergency_contact_name', 'emergency_contact_phone', 'relationship_to_patient')
        }),
        ("Medical Details", {
            'fields': ('blood_group', 'allergies', 'chronic_conditions', 'current_medications')
        }),
        ("Insurance & Status", {
            'fields': ('insurance_provider', 'insurance_policy_number', 'is_active')
        }),
        ("System Fields", {
            'fields': ('registration_date', 'last_updated'),
            'classes': ('collapse',),
        }),
    )

    # Set the number of products to display per page
    list_per_page = 50

    def save_model(self, request, obj, form, change):
        # Automatically set the user field to the currently logged-in user
        if not change or not obj.user:
            obj.user = request.user
        super().save_model(request, obj, form, change)
