# Generated by Django 5.1.3 on 2025-01-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patient_idx_patient_id',
            old_name='idx_patient_id',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patient_idx_email',
            old_name='idx_email',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patient_idx_phone',
            old_name='idx_phone',
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
