# Generated by Django 5.1.3 on 2025-05-08 12:18

import django.core.validators
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='bus', unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legal Name')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Type')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Registration Number')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Tax ID')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='VAT Number')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Primary Contact Number')),
                ('alternate_contact', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Alternate Contact')),
                ('hotline', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Hotline')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Business Email Address')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Support Email')),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business/', verbose_name='Business Logo')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Billing Address')),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Address')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=10, verbose_name='Default Currency')),
                ('fiscal_year_start', models.DateField(blank=True, null=True, verbose_name='Fiscal Year Start')),
                ('fiscal_year_end', models.DateField(blank=True, null=True, verbose_name='Fiscal Year End')),
                ('timezone', models.CharField(default='UTC', max_length=100, verbose_name='Timezone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Business Description')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Industry')),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Employees')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'indexes': [models.Index(fields=['name'], name='business_bu_name_217b62_idx'), models.Index(fields=['email'], name='business_bu_email_3abf43_idx'), models.Index(fields=['registration_number'], name='business_bu_registr_83790b_idx')],
            },
        ),
    ]
