# Generated by Django 5.1.3 on 2025-05-08 12:22

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='com', unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Type')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number')),
                ('hotline', models.CharField(blank=True, max_length=15, null=True, verbose_name='Hotline')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Company Logo')),
                ('address_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Address 1')),
                ('address_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Address 2')),
                ('address_invoice', models.CharField(blank=True, help_text='Address field for Invoice Print Copy', max_length=255, null=True, verbose_name='Company Address for Invoice')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('Country', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='Website')),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedIn', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
