# Generated by Django 5.1.3 on 2025-05-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_type',
            field=models.CharField(choices=[('exempt', 'Tax Exempt'), ('standard', 'Standard Rate'), ('reduced', 'Reduced Rate'), ('zero', 'Zero Rate')], default='standard', max_length=20),
        ),
    ]
